---
title: "ORC fish dashboard"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    navbar:
      - { title: "reproducible.co.nz", href: "https://reproducible.co.nz", align: right }
    orientation: rows
    vertical_layout: fill
    theme: spacelab
    source_code: embed 
---
<style>

body {
  padding-top: 70px;
}


.navbar-brand {
font-family: "Candara";
  font-weight: bold;
  font-size: 24px;
}


</style>


```{r}
library(sf)
library(tidyverse)
library(lubridate)
library(leaflet)
library(shiny)
library(shinyWidgets)
library(flexdashboard)
library(plotly)
library(viridis)
library(DT)
library(readxl)
library(factoextra)
library(leaflet.extras)
library(geojsonsf)
library(jsonify)
library(stringr)
library(janitor)
library(lwgeom) # for st_split
library(tidygraph)
library(sfnetworks)
library(igraph)
library(scales)
library(ggspatial)
```


Column {.sidebar data-width=350}
-------------------------------------
```{r}
renderPrint({
  
  lat <- round(input$map_click$lat, 2) 
  long <- if(input$map_click$lng > 180){
    input$map_click$lng * -1
    } else{
      input$map_click$lng
    }
  long <- round(input$map_click$lng, 2) 
  
  start <- c(long, lat)
  start
  
  
  textInput("start", label = "Click to start", value = start )
  
  rv$markers
   
})
```


```{r}
rv <- reactiveValues(markers = data.frame())
```


Column
-------------------------------------


```{r}
# for reasons which are unclear to me
# the output has to be called "map"

output$map  <- renderLeaflet({
 
  leaflet(options = leafletOptions(worldCopyJump = TRUE)) %>%
        setView(lng = 169,
          lat = -45.9,
          zoom = 8) %>%
    # add base maps
    addProviderTiles("Esri.WorldImagery",
                     # give the layer a name
                     group = "World")

  
})

icon.star <- makeAwesomeIcon(icon = 'star', markerColor = 'green', library='ion')

  observeEvent(input$map_click, {
    
    rv$markers <- rbind(rv$markers, data.frame(long = input$map_click$lng, lat = input$map_click$lat)
    )
    
       # If there are more than 2 markers, remove the oldest one
    if (nrow(rv$markers) > 2) {
      rv$markers <- rv$markers[-1,]
    }
    
    leafletProxy('map')%>%
      clearMarkers() %>%
      addAwesomeMarkers(lng = rv$markers$long, lat = rv$markers$lat, icon = icon.star)
  })
    
leafletOutput('map', height =900)
```


